#!/bin/sh
# runs hooks defined in .pre-commit-config.yaml on staged files
if command -v pre-commit > /dev/null 2>&1; then
    exec pre-commit run --hook-stage pre-commit
else
    echo "Git hook $(basename "$0") has been skipped as 'pre-commit' command is not available."
fi
